name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '00 00,12 * * *' # Runs every day, at midnight and noon
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in Luke MurrayNZ  posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://luke.geek.nz/feed"
          commit_message: "Updated README with the latest blog posts"
          date_format: "mmm d, yyyy"
          custom_tags: "postImage/featured_image/"
          disable_html_encoding: true
          item_exec: |
            post.description = post.description.replace(/<\/?[^>]+(>|$)/g, "").slice(0,100) 
          #template: '<table style="width:100%"><tr><td style="width:150px"><a href="$url"><img width="140px" src="https://raw.githubusercontent.com/PixelRobots/PixelRobots/master/images/PixelRobots_Desktop_Wallpaper.png"></a></td><td><a href="$url">$title</a> | $date <br> $description...</td></tr></table>$newline'            
          template: '<table style="width:100%"><tr><td style="width:150px"><a href="$url"><img width="280px" src="$postImage"></a></td><td><a href="$url">$title</a> | $date <br> $description...</td></tr></table>$newline'            
          #template: '<a href="$url"><img width="140px" src="https://github.com/PixelRobots/PixelRobots/blob/master/images/PixelRobots_Desktop_Wallpaper.png?raw=true"></a>$newline<td><a href="$url">$title</a><br/>$date$newline</br>'
